-- POSITION 값이 'FW'인 경우에만 1을 더한 값을 합산합니다.
-- 즉, 각 팀에서 FW(포워드) 포지션의 선수 수를 계산합니다.
-- ISNULL 함수는 결과가 NULL일 경우 0을 반환합니다.

SELECT TEAM_ID,
ISNULL(SUM(CASE WHEN POSITION = 'FW' THEN 1 END), 0) FW,
ISNULL(SUM(CASE WHEN POSITION = 'MF' THEN 1 END), 0) MF,
ISNULL(SUM(CASE WHEN POSITION = 'DK' THEN 1 END), 0) DF,
ISNULL(SUM(CASE WHEN POSITION = 'GK' THEN 1 END), 0) GK,
COUNT(*) SUM
FROM PLAYER
GROUP BY TEAM_ID;

-- ORACLE CODE
SELECT TEAM_ID,
       NVL(SUM(CASE WHEN POSITION = 'FW' THEN 1 END), 0) AS FW,
       NVL(SUM(CASE WHEN POSITION = 'MF' THEN 1 END), 0) AS MF,
       NVL(SUM(CASE WHEN POSITION = 'DF' THEN 1 END), 0) AS DF,
       NVL(SUM(CASE WHEN POSITION = 'GK' THEN 1 END), 0) AS GK,
       COUNT(*) AS SUM
FROM PLAYER
GROUP BY TEAM_ID;
